server:
  port: 80

spring:
  application:
    #应用名称 , 可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root3306
#  main:
#    #设置为 true 来自动中断循环
#    allow-circular-references: true

mybatis:
  configuration:
    #开启下划线与驼峰映射
    map-underscore-to-camel-case: true
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.qinan.reggie.entity


#设置pageHelper开关
pagehelper:
  auto-dialect: true
  reasonable: true